environment: 
  matrix:
    - node_version: "14"

#install scripts
install:

  - ps: Install-Product node $env:nodejs_version
#install modules
  - npm install

#output useful debugging
test_script:
  - node --version
  - npm --version

  - npm test

#Don't actually build
build: false